// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using football_draw_api.Data;

#nullable disable

namespace football_draw_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816072709_AddRefreshTokenToUser")]
    partial class AddRefreshTokenToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("football_draw_api.Models.Predictions.UserPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPredictions");
                });

            modelBuilder.Entity("football_draw_api.Models.Result.SeasonResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BallondOrId")
                        .HasColumnType("integer");

                    b.Property<string>("BallondOrName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChampionsLeagueWinnerId")
                        .HasColumnType("integer");

                    b.Property<string>("ChampionsLeagueWinnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CopaReyWinnerId")
                        .HasColumnType("integer");

                    b.Property<string>("CopaReyWinnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisappointmentPlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("DisappointmentPlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GoldenBootId")
                        .HasColumnType("integer");

                    b.Property<string>("GoldenBootName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LaLigaWinnerId")
                        .HasColumnType("integer");

                    b.Property<string>("LaLigaWinnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StandOutPlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("StandOutPlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuperCopaWinnerId")
                        .HasColumnType("integer");

                    b.Property<string>("SuperCopaWinnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopScorerId")
                        .HasColumnType("integer");

                    b.Property<string>("TopScorerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZamoraWinnerId")
                        .HasColumnType("integer");

                    b.Property<string>("ZamoraWinnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SeasonResults");
                });

            modelBuilder.Entity("football_draw_api.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("football_draw_api.Models.Predictions.UserPrediction", b =>
                {
                    b.HasOne("football_draw_api.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("football_draw_api.Models.Predictions.SeasonPrediction", "SeasonPrediction", b1 =>
                        {
                            b1.Property<int>("UserPredictionId")
                                .HasColumnType("integer");

                            b1.Property<int>("BallondOrId")
                                .HasColumnType("integer");

                            b1.Property<string>("BallondOrName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("ChampionsLeagueWinnerId")
                                .HasColumnType("integer");

                            b1.Property<string>("ChampionsLeagueWinnerName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("CopaReyWinnerId")
                                .HasColumnType("integer");

                            b1.Property<string>("CopaReyWinnerName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("DisappointmentPlayerId")
                                .HasColumnType("integer");

                            b1.Property<string>("DisappointmentPlayerName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("GoldenBootId")
                                .HasColumnType("integer");

                            b1.Property<string>("GoldenBootName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("LaLigaWinnerId")
                                .HasColumnType("integer");

                            b1.Property<string>("LaLigaWinnerName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("StandOutPlayerId")
                                .HasColumnType("integer");

                            b1.Property<string>("StandOutPlayerName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("SuperCopaWinnerId")
                                .HasColumnType("integer");

                            b1.Property<string>("SuperCopaWinnerName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("TopScorerId")
                                .HasColumnType("integer");

                            b1.Property<string>("TopScorerName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("ZamoraWinnerId")
                                .HasColumnType("integer");

                            b1.Property<string>("ZamoraWinnerName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserPredictionId");

                            b1.ToTable("UserPredictions");

                            b1.WithOwner()
                                .HasForeignKey("UserPredictionId");
                        });

                    b.Navigation("SeasonPrediction")
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
